language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

services:
  - redis-server

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION}

script:
  - vendor/bin/phpunit --coverage-clover=build/phpunit.clover
  - vendor/bin/phpspec run

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/phpunit.clover
  - php ocular.phar code-coverage:upload --format=php-clover build/phpspec.clover
