language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

before_install:
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION}

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpspec
