language: php

services:
  - redis-server

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

sudo: required

cache:
  directories:
    - $HOME/.composer/cache/files

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - composer self-update

install: composer update --prefer-source $COMPOSER_FLAGS

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
