language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.4.*
  - SYMFONY_VERSION=2.5.*

services:
  - redis-server

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq beanstalkd
  - sudo beanstalkd -d -l 127.0.0.1 -p 11300
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "extension = redis.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi'
  - composer require --no-update symfony/yaml:${SYMFONY_VERSION}
  - composer require --no-update symfony/finder:${SYMFONY_VERSION}
  - composer require symfony/event-dispatcher:${SYMFONY_VERSION}

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpspec run --format=pretty

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
